### ISSUE TITLE
Error All elements in 'pie' must be between 0 and 1.

### ISSUE THREAD

**Issue by paganantonio** [jmbh/tvvar_paper#1]
Hello, 
I am running into a problem where the pred_obj$tverrors is returning negative values. Have you seen this issue in the past?

![image](https://user-images.githubusercontent.com/67159452/85149812-5b102c80-b217-11ea-85ed-e8bcac6bf484.png)
Thanks!
Best, 
-Antonio

**Comment by jmbh** [comment]
Hi Antonio, 

This is a question about mgm, so ideally please use the issues in https://github.com/jmbh/mgm.

To answer your question: sometimes the model can overfit and then you can get negative R2 values. Those should be very small though. In practice, I would simply set those negative R2s to zero.

Jonas

**Comment by paganantonio** [comment]
Hi Jonas,
Thank you for the prompt response! How would you recommend I set those R2 values to zero within the code? Is there a feature of which I can tell the program to set any negative values of pred+obj$tverrors to 0?
Thanks!
Best,


Antonio Pagan

Texas Tech University - Doctoral Student

Individualized Cognitive Behavioral Assessment and Treatment Lab



________________________________
